### PR TITLE
HH code with Checkstyle and Travis

### PR DESCRIPTION
**Pull request by thefangbear**
Fixes various issues in code that does not go along with checkstyle requirements. Checkstyle re-enabled

### CODE REVIEW

**Comment by thefangbear** [comment]
@aaplmath review please

**Comment by thefangbear** [comment]
I'm going to leave this open to remind us to test the code.

**Review by jrr6 — COMMENTED** [review]
Can we add the Travis integration to this so that it'll display as passing? (The .travis.yml file is already on the travis branch.)

**Comment by jrr6** [comment]
This pull request now includes the `.travis.yml` file so that it will appear as passing. Additionally, we ought now be using Travis anyway to ensure builds are passing.

**Comment by thefangbear** [comment]
I'll merge?

**Comment by jrr6** [comment]
@thefangbear No! It still needs to be tested.

**Comment by thefangbear** [comment]
OK.

**Comment by thefangbear** [comment]
(I thought that you were testing it today)

**Review by jrr6 — APPROVED** [review]
Tested and confirmed working

**Pull request merged**
